# docker build -t tinyproxy .
version: '2'
services:
  tinyproxy:
    image: w3fibonacci/tinyproxy
    container_name: tinyproxy
    hostname: tinyproxy
    restart: always
    volumes:
    - ./custom.conf:/etc/tinyproxy.conf
    tty: true
    ports:
      - 8888:8888
